// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: symbol_his_matu_yld.proto

#ifndef PROTOBUF_symbol_5fhis_5fmatu_5fyld_2eproto__INCLUDED
#define PROTOBUF_symbol_5fhis_5fmatu_5fyld_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace chaos_data {
class SymbolHisMatuYld;
class SymbolHisMatuYldDefaultTypeInternal;
extern SymbolHisMatuYldDefaultTypeInternal _SymbolHisMatuYld_default_instance_;
}  // namespace chaos_data

namespace chaos_data {

namespace protobuf_symbol_5fhis_5fmatu_5fyld_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_symbol_5fhis_5fmatu_5fyld_2eproto

// ===================================================================

class SymbolHisMatuYld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chaos_data.SymbolHisMatuYld) */ {
 public:
  SymbolHisMatuYld();
  virtual ~SymbolHisMatuYld();

  SymbolHisMatuYld(const SymbolHisMatuYld& from);

  inline SymbolHisMatuYld& operator=(const SymbolHisMatuYld& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SymbolHisMatuYld& default_instance();

  static inline const SymbolHisMatuYld* internal_default_instance() {
    return reinterpret_cast<const SymbolHisMatuYld*>(
               &_SymbolHisMatuYld_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SymbolHisMatuYld* other);

  // implements Message ----------------------------------------------

  inline SymbolHisMatuYld* New() const PROTOBUF_FINAL { return New(NULL); }

  SymbolHisMatuYld* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SymbolHisMatuYld& from);
  void MergeFrom(const SymbolHisMatuYld& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SymbolHisMatuYld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::uint32 time() const;
  void set_time(::google::protobuf::uint32 value);

  // optional float value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  float value() const;
  void set_value(float value);

  // @@protoc_insertion_point(class_scope:chaos_data.SymbolHisMatuYld)
 private:
  void set_has_time();
  void clear_has_time();
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 time_;
  float value_;
  friend struct protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SymbolHisMatuYld

// optional uint32 time = 1;
inline bool SymbolHisMatuYld::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SymbolHisMatuYld::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SymbolHisMatuYld::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SymbolHisMatuYld::clear_time() {
  time_ = 0u;
  clear_has_time();
}
inline ::google::protobuf::uint32 SymbolHisMatuYld::time() const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolHisMatuYld.time)
  return time_;
}
inline void SymbolHisMatuYld::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:chaos_data.SymbolHisMatuYld.time)
}

// optional float value = 2;
inline bool SymbolHisMatuYld::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SymbolHisMatuYld::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SymbolHisMatuYld::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SymbolHisMatuYld::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline float SymbolHisMatuYld::value() const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolHisMatuYld.value)
  return value_;
}
inline void SymbolHisMatuYld::set_value(float value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:chaos_data.SymbolHisMatuYld.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace chaos_data

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_symbol_5fhis_5fmatu_5fyld_2eproto__INCLUDED
