// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: symbol_l2_order_state.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "symbol_l2_order_state.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace chaos_data {
class SymbolL2OrderState_SymbolOrderStatDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SymbolL2OrderState_SymbolOrderStat>
     _instance;
} _SymbolL2OrderState_SymbolOrderStat_default_instance_;
class SymbolL2OrderStateDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SymbolL2OrderState>
     _instance;
} _SymbolL2OrderState_default_instance_;

namespace protobuf_symbol_5fl2_5forder_5fstate_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, buy_order_vol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, sell_order_vol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, order_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState_SymbolOrderStat, vol_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolL2OrderState, order_state_),
  1,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(SymbolL2OrderState_SymbolOrderStat)},
  { 13, 20, sizeof(SymbolL2OrderState)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SymbolL2OrderState_SymbolOrderStat_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SymbolL2OrderState_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "symbol_l2_order_state.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SymbolL2OrderState_SymbolOrderStat_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_SymbolL2OrderState_SymbolOrderStat_default_instance_);_SymbolL2OrderState_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_SymbolL2OrderState_default_instance_);_SymbolL2OrderState_default_instance_._instance.get_mutable()->order_state_ = const_cast< ::chaos_data::SymbolL2OrderState_SymbolOrderStat*>(
      ::chaos_data::SymbolL2OrderState_SymbolOrderStat::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033symbol_l2_order_state.proto\022\nchaos_dat"
      "a\"\311\001\n\022SymbolL2OrderState\022\014\n\004time\030\001 \002(\r\022C"
      "\n\013order_state\030\002 \001(\0132..chaos_data.SymbolL"
      "2OrderState.SymbolOrderStat\032`\n\017SymbolOrd"
      "erStat\022\025\n\rbuy_order_vol\030\001 \003(\004\022\026\n\016sell_or"
      "der_vol\030\002 \003(\004\022\021\n\torder_num\030\003 \003(\004\022\013\n\003vol\030"
      "\004 \003(\004"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 245);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "symbol_l2_order_state.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_symbol_5fl2_5forder_5fstate_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolL2OrderState_SymbolOrderStat::kBuyOrderVolFieldNumber;
const int SymbolL2OrderState_SymbolOrderStat::kSellOrderVolFieldNumber;
const int SymbolL2OrderState_SymbolOrderStat::kOrderNumFieldNumber;
const int SymbolL2OrderState_SymbolOrderStat::kVolFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolL2OrderState_SymbolOrderStat::SymbolL2OrderState_SymbolOrderStat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_symbol_5fl2_5forder_5fstate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:chaos_data.SymbolL2OrderState.SymbolOrderStat)
}
SymbolL2OrderState_SymbolOrderStat::SymbolL2OrderState_SymbolOrderStat(const SymbolL2OrderState_SymbolOrderStat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      buy_order_vol_(from.buy_order_vol_),
      sell_order_vol_(from.sell_order_vol_),
      order_num_(from.order_num_),
      vol_(from.vol_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:chaos_data.SymbolL2OrderState.SymbolOrderStat)
}

void SymbolL2OrderState_SymbolOrderStat::SharedCtor() {
  _cached_size_ = 0;
}

SymbolL2OrderState_SymbolOrderStat::~SymbolL2OrderState_SymbolOrderStat() {
  // @@protoc_insertion_point(destructor:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  SharedDtor();
}

void SymbolL2OrderState_SymbolOrderStat::SharedDtor() {
}

void SymbolL2OrderState_SymbolOrderStat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolL2OrderState_SymbolOrderStat::descriptor() {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fl2_5forder_5fstate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolL2OrderState_SymbolOrderStat& SymbolL2OrderState_SymbolOrderStat::default_instance() {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::InitDefaults();
  return *internal_default_instance();
}

SymbolL2OrderState_SymbolOrderStat* SymbolL2OrderState_SymbolOrderStat::New(::google::protobuf::Arena* arena) const {
  SymbolL2OrderState_SymbolOrderStat* n = new SymbolL2OrderState_SymbolOrderStat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SymbolL2OrderState_SymbolOrderStat::Clear() {
// @@protoc_insertion_point(message_clear_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  buy_order_vol_.Clear();
  sell_order_vol_.Clear();
  order_num_.Clear();
  vol_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SymbolL2OrderState_SymbolOrderStat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint64 buy_order_vol = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 8u, input, this->mutable_buy_order_vol())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_buy_order_vol())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint64 sell_order_vol = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16u, input, this->mutable_sell_order_vol())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_sell_order_vol())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint64 order_num = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 24u, input, this->mutable_order_num())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_order_num())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint64 vol = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 32u, input, this->mutable_vol())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_vol())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  return false;
#undef DO_
}

void SymbolL2OrderState_SymbolOrderStat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint64 buy_order_vol = 1;
  for (int i = 0, n = this->buy_order_vol_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      1, this->buy_order_vol(i), output);
  }

  // repeated uint64 sell_order_vol = 2;
  for (int i = 0, n = this->sell_order_vol_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->sell_order_vol(i), output);
  }

  // repeated uint64 order_num = 3;
  for (int i = 0, n = this->order_num_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      3, this->order_num(i), output);
  }

  // repeated uint64 vol = 4;
  for (int i = 0, n = this->vol_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      4, this->vol(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:chaos_data.SymbolL2OrderState.SymbolOrderStat)
}

::google::protobuf::uint8* SymbolL2OrderState_SymbolOrderStat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint64 buy_order_vol = 1;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(1, this->buy_order_vol_, target);

  // repeated uint64 sell_order_vol = 2;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(2, this->sell_order_vol_, target);

  // repeated uint64 order_num = 3;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(3, this->order_num_, target);

  // repeated uint64 vol = 4;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(4, this->vol_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  return target;
}

size_t SymbolL2OrderState_SymbolOrderStat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated uint64 buy_order_vol = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->buy_order_vol_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->buy_order_vol_size());
    total_size += data_size;
  }

  // repeated uint64 sell_order_vol = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->sell_order_vol_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->sell_order_vol_size());
    total_size += data_size;
  }

  // repeated uint64 order_num = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->order_num_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->order_num_size());
    total_size += data_size;
  }

  // repeated uint64 vol = 4;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->vol_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->vol_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolL2OrderState_SymbolOrderStat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolL2OrderState_SymbolOrderStat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolL2OrderState_SymbolOrderStat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chaos_data.SymbolL2OrderState.SymbolOrderStat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chaos_data.SymbolL2OrderState.SymbolOrderStat)
    MergeFrom(*source);
  }
}

void SymbolL2OrderState_SymbolOrderStat::MergeFrom(const SymbolL2OrderState_SymbolOrderStat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  buy_order_vol_.MergeFrom(from.buy_order_vol_);
  sell_order_vol_.MergeFrom(from.sell_order_vol_);
  order_num_.MergeFrom(from.order_num_);
  vol_.MergeFrom(from.vol_);
}

void SymbolL2OrderState_SymbolOrderStat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolL2OrderState_SymbolOrderStat::CopyFrom(const SymbolL2OrderState_SymbolOrderStat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chaos_data.SymbolL2OrderState.SymbolOrderStat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolL2OrderState_SymbolOrderStat::IsInitialized() const {
  return true;
}

void SymbolL2OrderState_SymbolOrderStat::Swap(SymbolL2OrderState_SymbolOrderStat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolL2OrderState_SymbolOrderStat::InternalSwap(SymbolL2OrderState_SymbolOrderStat* other) {
  using std::swap;
  buy_order_vol_.InternalSwap(&other->buy_order_vol_);
  sell_order_vol_.InternalSwap(&other->sell_order_vol_);
  order_num_.InternalSwap(&other->order_num_);
  vol_.InternalSwap(&other->vol_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolL2OrderState_SymbolOrderStat::GetMetadata() const {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fl2_5forder_5fstate_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SymbolL2OrderState_SymbolOrderStat

// repeated uint64 buy_order_vol = 1;
int SymbolL2OrderState_SymbolOrderStat::buy_order_vol_size() const {
  return buy_order_vol_.size();
}
void SymbolL2OrderState_SymbolOrderStat::clear_buy_order_vol() {
  buy_order_vol_.Clear();
}
::google::protobuf::uint64 SymbolL2OrderState_SymbolOrderStat::buy_order_vol(int index) const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.SymbolOrderStat.buy_order_vol)
  return buy_order_vol_.Get(index);
}
void SymbolL2OrderState_SymbolOrderStat::set_buy_order_vol(int index, ::google::protobuf::uint64 value) {
  buy_order_vol_.Set(index, value);
  // @@protoc_insertion_point(field_set:chaos_data.SymbolL2OrderState.SymbolOrderStat.buy_order_vol)
}
void SymbolL2OrderState_SymbolOrderStat::add_buy_order_vol(::google::protobuf::uint64 value) {
  buy_order_vol_.Add(value);
  // @@protoc_insertion_point(field_add:chaos_data.SymbolL2OrderState.SymbolOrderStat.buy_order_vol)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SymbolL2OrderState_SymbolOrderStat::buy_order_vol() const {
  // @@protoc_insertion_point(field_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.buy_order_vol)
  return buy_order_vol_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SymbolL2OrderState_SymbolOrderStat::mutable_buy_order_vol() {
  // @@protoc_insertion_point(field_mutable_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.buy_order_vol)
  return &buy_order_vol_;
}

// repeated uint64 sell_order_vol = 2;
int SymbolL2OrderState_SymbolOrderStat::sell_order_vol_size() const {
  return sell_order_vol_.size();
}
void SymbolL2OrderState_SymbolOrderStat::clear_sell_order_vol() {
  sell_order_vol_.Clear();
}
::google::protobuf::uint64 SymbolL2OrderState_SymbolOrderStat::sell_order_vol(int index) const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.SymbolOrderStat.sell_order_vol)
  return sell_order_vol_.Get(index);
}
void SymbolL2OrderState_SymbolOrderStat::set_sell_order_vol(int index, ::google::protobuf::uint64 value) {
  sell_order_vol_.Set(index, value);
  // @@protoc_insertion_point(field_set:chaos_data.SymbolL2OrderState.SymbolOrderStat.sell_order_vol)
}
void SymbolL2OrderState_SymbolOrderStat::add_sell_order_vol(::google::protobuf::uint64 value) {
  sell_order_vol_.Add(value);
  // @@protoc_insertion_point(field_add:chaos_data.SymbolL2OrderState.SymbolOrderStat.sell_order_vol)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SymbolL2OrderState_SymbolOrderStat::sell_order_vol() const {
  // @@protoc_insertion_point(field_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.sell_order_vol)
  return sell_order_vol_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SymbolL2OrderState_SymbolOrderStat::mutable_sell_order_vol() {
  // @@protoc_insertion_point(field_mutable_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.sell_order_vol)
  return &sell_order_vol_;
}

// repeated uint64 order_num = 3;
int SymbolL2OrderState_SymbolOrderStat::order_num_size() const {
  return order_num_.size();
}
void SymbolL2OrderState_SymbolOrderStat::clear_order_num() {
  order_num_.Clear();
}
::google::protobuf::uint64 SymbolL2OrderState_SymbolOrderStat::order_num(int index) const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.SymbolOrderStat.order_num)
  return order_num_.Get(index);
}
void SymbolL2OrderState_SymbolOrderStat::set_order_num(int index, ::google::protobuf::uint64 value) {
  order_num_.Set(index, value);
  // @@protoc_insertion_point(field_set:chaos_data.SymbolL2OrderState.SymbolOrderStat.order_num)
}
void SymbolL2OrderState_SymbolOrderStat::add_order_num(::google::protobuf::uint64 value) {
  order_num_.Add(value);
  // @@protoc_insertion_point(field_add:chaos_data.SymbolL2OrderState.SymbolOrderStat.order_num)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SymbolL2OrderState_SymbolOrderStat::order_num() const {
  // @@protoc_insertion_point(field_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.order_num)
  return order_num_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SymbolL2OrderState_SymbolOrderStat::mutable_order_num() {
  // @@protoc_insertion_point(field_mutable_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.order_num)
  return &order_num_;
}

// repeated uint64 vol = 4;
int SymbolL2OrderState_SymbolOrderStat::vol_size() const {
  return vol_.size();
}
void SymbolL2OrderState_SymbolOrderStat::clear_vol() {
  vol_.Clear();
}
::google::protobuf::uint64 SymbolL2OrderState_SymbolOrderStat::vol(int index) const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.SymbolOrderStat.vol)
  return vol_.Get(index);
}
void SymbolL2OrderState_SymbolOrderStat::set_vol(int index, ::google::protobuf::uint64 value) {
  vol_.Set(index, value);
  // @@protoc_insertion_point(field_set:chaos_data.SymbolL2OrderState.SymbolOrderStat.vol)
}
void SymbolL2OrderState_SymbolOrderStat::add_vol(::google::protobuf::uint64 value) {
  vol_.Add(value);
  // @@protoc_insertion_point(field_add:chaos_data.SymbolL2OrderState.SymbolOrderStat.vol)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SymbolL2OrderState_SymbolOrderStat::vol() const {
  // @@protoc_insertion_point(field_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.vol)
  return vol_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SymbolL2OrderState_SymbolOrderStat::mutable_vol() {
  // @@protoc_insertion_point(field_mutable_list:chaos_data.SymbolL2OrderState.SymbolOrderStat.vol)
  return &vol_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolL2OrderState::kTimeFieldNumber;
const int SymbolL2OrderState::kOrderStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolL2OrderState::SymbolL2OrderState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_symbol_5fl2_5forder_5fstate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:chaos_data.SymbolL2OrderState)
}
SymbolL2OrderState::SymbolL2OrderState(const SymbolL2OrderState& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_order_state()) {
    order_state_ = new ::chaos_data::SymbolL2OrderState_SymbolOrderStat(*from.order_state_);
  } else {
    order_state_ = NULL;
  }
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:chaos_data.SymbolL2OrderState)
}

void SymbolL2OrderState::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&order_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&time_) -
      reinterpret_cast<char*>(&order_state_)) + sizeof(time_));
}

SymbolL2OrderState::~SymbolL2OrderState() {
  // @@protoc_insertion_point(destructor:chaos_data.SymbolL2OrderState)
  SharedDtor();
}

void SymbolL2OrderState::SharedDtor() {
  if (this != internal_default_instance()) delete order_state_;
}

void SymbolL2OrderState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolL2OrderState::descriptor() {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fl2_5forder_5fstate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolL2OrderState& SymbolL2OrderState::default_instance() {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::InitDefaults();
  return *internal_default_instance();
}

SymbolL2OrderState* SymbolL2OrderState::New(::google::protobuf::Arena* arena) const {
  SymbolL2OrderState* n = new SymbolL2OrderState;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SymbolL2OrderState::Clear() {
// @@protoc_insertion_point(message_clear_start:chaos_data.SymbolL2OrderState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (has_order_state()) {
    GOOGLE_DCHECK(order_state_ != NULL);
    order_state_->::chaos_data::SymbolL2OrderState_SymbolOrderStat::Clear();
  }
  time_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SymbolL2OrderState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chaos_data.SymbolL2OrderState)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .chaos_data.SymbolL2OrderState.SymbolOrderStat order_state = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_order_state()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chaos_data.SymbolL2OrderState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chaos_data.SymbolL2OrderState)
  return false;
#undef DO_
}

void SymbolL2OrderState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chaos_data.SymbolL2OrderState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 time = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->time(), output);
  }

  // optional .chaos_data.SymbolL2OrderState.SymbolOrderStat order_state = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->order_state_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:chaos_data.SymbolL2OrderState)
}

::google::protobuf::uint8* SymbolL2OrderState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:chaos_data.SymbolL2OrderState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 time = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->time(), target);
  }

  // optional .chaos_data.SymbolL2OrderState.SymbolOrderStat order_state = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->order_state_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chaos_data.SymbolL2OrderState)
  return target;
}

size_t SymbolL2OrderState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chaos_data.SymbolL2OrderState)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint32 time = 1;
  if (has_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->time());
  }
  // optional .chaos_data.SymbolL2OrderState.SymbolOrderStat order_state = 2;
  if (has_order_state()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->order_state_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolL2OrderState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chaos_data.SymbolL2OrderState)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolL2OrderState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolL2OrderState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chaos_data.SymbolL2OrderState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chaos_data.SymbolL2OrderState)
    MergeFrom(*source);
  }
}

void SymbolL2OrderState::MergeFrom(const SymbolL2OrderState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chaos_data.SymbolL2OrderState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_order_state()->::chaos_data::SymbolL2OrderState_SymbolOrderStat::MergeFrom(from.order_state());
    }
    if (cached_has_bits & 0x00000002u) {
      time_ = from.time_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SymbolL2OrderState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chaos_data.SymbolL2OrderState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolL2OrderState::CopyFrom(const SymbolL2OrderState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chaos_data.SymbolL2OrderState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolL2OrderState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void SymbolL2OrderState::Swap(SymbolL2OrderState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolL2OrderState::InternalSwap(SymbolL2OrderState* other) {
  using std::swap;
  swap(order_state_, other->order_state_);
  swap(time_, other->time_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolL2OrderState::GetMetadata() const {
  protobuf_symbol_5fl2_5forder_5fstate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fl2_5forder_5fstate_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SymbolL2OrderState

// required uint32 time = 1;
bool SymbolL2OrderState::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SymbolL2OrderState::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
void SymbolL2OrderState::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
void SymbolL2OrderState::clear_time() {
  time_ = 0u;
  clear_has_time();
}
::google::protobuf::uint32 SymbolL2OrderState::time() const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.time)
  return time_;
}
void SymbolL2OrderState::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:chaos_data.SymbolL2OrderState.time)
}

// optional .chaos_data.SymbolL2OrderState.SymbolOrderStat order_state = 2;
bool SymbolL2OrderState::has_order_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SymbolL2OrderState::set_has_order_state() {
  _has_bits_[0] |= 0x00000001u;
}
void SymbolL2OrderState::clear_has_order_state() {
  _has_bits_[0] &= ~0x00000001u;
}
void SymbolL2OrderState::clear_order_state() {
  if (order_state_ != NULL) order_state_->::chaos_data::SymbolL2OrderState_SymbolOrderStat::Clear();
  clear_has_order_state();
}
const ::chaos_data::SymbolL2OrderState_SymbolOrderStat& SymbolL2OrderState::order_state() const {
  const ::chaos_data::SymbolL2OrderState_SymbolOrderStat* p = order_state_;
  // @@protoc_insertion_point(field_get:chaos_data.SymbolL2OrderState.order_state)
  return p != NULL ? *p : *reinterpret_cast<const ::chaos_data::SymbolL2OrderState_SymbolOrderStat*>(
      &::chaos_data::_SymbolL2OrderState_SymbolOrderStat_default_instance_);
}
::chaos_data::SymbolL2OrderState_SymbolOrderStat* SymbolL2OrderState::mutable_order_state() {
  set_has_order_state();
  if (order_state_ == NULL) {
    order_state_ = new ::chaos_data::SymbolL2OrderState_SymbolOrderStat;
  }
  // @@protoc_insertion_point(field_mutable:chaos_data.SymbolL2OrderState.order_state)
  return order_state_;
}
::chaos_data::SymbolL2OrderState_SymbolOrderStat* SymbolL2OrderState::release_order_state() {
  // @@protoc_insertion_point(field_release:chaos_data.SymbolL2OrderState.order_state)
  clear_has_order_state();
  ::chaos_data::SymbolL2OrderState_SymbolOrderStat* temp = order_state_;
  order_state_ = NULL;
  return temp;
}
void SymbolL2OrderState::set_allocated_order_state(::chaos_data::SymbolL2OrderState_SymbolOrderStat* order_state) {
  delete order_state_;
  order_state_ = order_state;
  if (order_state) {
    set_has_order_state();
  } else {
    clear_has_order_state();
  }
  // @@protoc_insertion_point(field_set_allocated:chaos_data.SymbolL2OrderState.order_state)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace chaos_data

// @@protoc_insertion_point(global_scope)
