// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: symbol_his_matu_yld.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "symbol_his_matu_yld.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace chaos_data {
class SymbolHisMatuYldDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SymbolHisMatuYld> {
} _SymbolHisMatuYld_default_instance_;

namespace protobuf_symbol_5fhis_5fmatu_5fyld_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolHisMatuYld, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolHisMatuYld, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolHisMatuYld, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SymbolHisMatuYld, value_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(SymbolHisMatuYld)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SymbolHisMatuYld_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "symbol_his_matu_yld.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _SymbolHisMatuYld_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SymbolHisMatuYld_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\031symbol_his_matu_yld.proto\022\nchaos_data\""
      "/\n\020SymbolHisMatuYld\022\014\n\004time\030\001 \001(\r\022\r\n\005val"
      "ue\030\002 \001(\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 88);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "symbol_his_matu_yld.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_symbol_5fhis_5fmatu_5fyld_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SymbolHisMatuYld::kTimeFieldNumber;
const int SymbolHisMatuYld::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SymbolHisMatuYld::SymbolHisMatuYld()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:chaos_data.SymbolHisMatuYld)
}
SymbolHisMatuYld::SymbolHisMatuYld(const SymbolHisMatuYld& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&time_, &from.time_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&time_)) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:chaos_data.SymbolHisMatuYld)
}

void SymbolHisMatuYld::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&time_)) + sizeof(value_));
}

SymbolHisMatuYld::~SymbolHisMatuYld() {
  // @@protoc_insertion_point(destructor:chaos_data.SymbolHisMatuYld)
  SharedDtor();
}

void SymbolHisMatuYld::SharedDtor() {
}

void SymbolHisMatuYld::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SymbolHisMatuYld::descriptor() {
  protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SymbolHisMatuYld& SymbolHisMatuYld::default_instance() {
  protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::InitDefaults();
  return *internal_default_instance();
}

SymbolHisMatuYld* SymbolHisMatuYld::New(::google::protobuf::Arena* arena) const {
  SymbolHisMatuYld* n = new SymbolHisMatuYld;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SymbolHisMatuYld::Clear() {
// @@protoc_insertion_point(message_clear_start:chaos_data.SymbolHisMatuYld)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&time_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&value_) -
        reinterpret_cast<char*>(&time_)) + sizeof(value_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SymbolHisMatuYld::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chaos_data.SymbolHisMatuYld)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u)) {
          set_has_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chaos_data.SymbolHisMatuYld)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chaos_data.SymbolHisMatuYld)
  return false;
#undef DO_
}

void SymbolHisMatuYld::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chaos_data.SymbolHisMatuYld)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 time = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->time(), output);
  }

  // optional float value = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:chaos_data.SymbolHisMatuYld)
}

::google::protobuf::uint8* SymbolHisMatuYld::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chaos_data.SymbolHisMatuYld)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 time = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->time(), target);
  }

  // optional float value = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chaos_data.SymbolHisMatuYld)
  return target;
}

size_t SymbolHisMatuYld::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chaos_data.SymbolHisMatuYld)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional uint32 time = 1;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->time());
    }

    // optional float value = 2;
    if (has_value()) {
      total_size += 1 + 4;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SymbolHisMatuYld::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chaos_data.SymbolHisMatuYld)
  GOOGLE_DCHECK_NE(&from, this);
  const SymbolHisMatuYld* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SymbolHisMatuYld>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chaos_data.SymbolHisMatuYld)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chaos_data.SymbolHisMatuYld)
    MergeFrom(*source);
  }
}

void SymbolHisMatuYld::MergeFrom(const SymbolHisMatuYld& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chaos_data.SymbolHisMatuYld)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      time_ = from.time_;
    }
    if (cached_has_bits & 0x00000002u) {
      value_ = from.value_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SymbolHisMatuYld::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chaos_data.SymbolHisMatuYld)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SymbolHisMatuYld::CopyFrom(const SymbolHisMatuYld& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chaos_data.SymbolHisMatuYld)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SymbolHisMatuYld::IsInitialized() const {
  return true;
}

void SymbolHisMatuYld::Swap(SymbolHisMatuYld* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SymbolHisMatuYld::InternalSwap(SymbolHisMatuYld* other) {
  std::swap(time_, other->time_);
  std::swap(value_, other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SymbolHisMatuYld::GetMetadata() const {
  protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_symbol_5fhis_5fmatu_5fyld_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SymbolHisMatuYld

// optional uint32 time = 1;
bool SymbolHisMatuYld::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SymbolHisMatuYld::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
void SymbolHisMatuYld::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
void SymbolHisMatuYld::clear_time() {
  time_ = 0u;
  clear_has_time();
}
::google::protobuf::uint32 SymbolHisMatuYld::time() const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolHisMatuYld.time)
  return time_;
}
void SymbolHisMatuYld::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:chaos_data.SymbolHisMatuYld.time)
}

// optional float value = 2;
bool SymbolHisMatuYld::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SymbolHisMatuYld::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
void SymbolHisMatuYld::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
void SymbolHisMatuYld::clear_value() {
  value_ = 0;
  clear_has_value();
}
float SymbolHisMatuYld::value() const {
  // @@protoc_insertion_point(field_get:chaos_data.SymbolHisMatuYld.value)
  return value_;
}
void SymbolHisMatuYld::set_value(float value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:chaos_data.SymbolHisMatuYld.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace chaos_data

// @@protoc_insertion_point(global_scope)
